Feature like&bookmark
bhtibrewal/artsy-social pull request #5
Opened 2022-05-05 17:32 UTC by bhtibrewal

- the UI for a single post page is WIP.
- added comments are only visible on single post page
- to go to the single post page click on 'n Comment'

pages to check:
- src/components/user_section/UserSection.jsx
- src/components/card/PostCard.jsx
- src/components/comment_section/CommentSection.jsx

2022-05-05 18:00 UTC, Naman-Saxena1 requested changes
I tried liking and bookmarking post, it redirects to login page but when I try login as guest, I am unable to login, so maybe you can cross check that.

1. Create Post and Post component should have same width to get alignment.
2. I suggest you disable textarea horizontal resize using resize: vertical; property on it.
![Capture1](https://user-images.githubusercontent.com/90456667/166984660-39f2b066-b103-4607-babd-0b05531d42af.PNG)

2022-05-05 18:00 UTC, Naman-Saxena1 commented on src/components/card/PostCard.jsx
> +      <UserSection user={{ username, profile_pic, firstName, lastName }} />
This is fine but if you are just passing to other component and again destructuring in UserSection.jsx Line 5.
I think you can just directly pass object without extra destructuring at Line 68

2022-05-05 19:18 UTC, SinchanaMS approved these changes
The code looks good.
However, there are some issues I found in the UI, please look into them.

1. Guest login is not working.
2. The error toast when the user is not logged in is not showing the error message.
3. The post text-area is resizing beyond the container horizontally. Either enable only vertical resize or add a limit to the horizontal resize property to not overflow.

2022-05-05 19:18 UTC, SinchanaMS commented on src/pages/auth/sign_in/SignIn.jsx
> +  console.log(location);
Remove logs after checks.

2022-05-05 19:18 UTC, SinchanaMS commented on src/services/posts/addComment.js
> +        showToast({ title: e?.response?.errors, type: 'error' });
Please check if this is working. I can see only the toast, and no message when I try adding the comment.
![image](https://user-images.githubusercontent.com/94738532/167008706-2efc349f-b117-44fd-8a59-4e164f7da84b.png)

2022-05-05 19:18 UTC, SinchanaMS commented on src/services/posts/likePost.js
> +        console.log(res)
Please remove the log here too.

2022-05-06 04:13 UTC, iprankurpandey approved these changes

2022-05-06 04:14 UTC, iprankurpandey commented
all code looks good to me , however login as guest isnt working

2022-05-06 07:58 UTC, merged